apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2CRHK8wEJoLJif0JkAOiY9Skml9SoP/DPJMGzlRkelAIaUkg,iv:E+fc+vYEjIU/OGNYvg3B1WeVn8uKYgr89IdSJbfPFBA=,tag:5v9n5P3p+aHjgLTgNLBIcg==,type:str]
    credentials.json: ENC[AES256_GCM,data:gGEOljwOxWApVqLfCL7cl8yaiMAR51sAdfyhNburLAd3oAWq6UASjxCGsCLg8jcIK3lv0CX4Q1jWFxnJSYyhKXWh6oPluGrXVWLKLBxwOMKfrWQwRPyKFLOLxhaArWe5urDyFKNBDF9y9oQpA+/q+EwD+9aXPuCtQGD/zweLOtL3H+geSsoxrBVDuegxjSwIkyQxzEfiSQYROX1dGQ4v91joUkfyrLlxE0fPRib70g==,iv:G/b4CKZsbfu/bQLXrUqISkZLuOm6zfTTIVgVWf/2AlY=,tag:L4Qi9EcfEaMITzfPTQLkMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQU5hR0hMV1pwbHk5b1Bq
            b3BqMFl1NXN4OHJaNUxZZ1VYdzBvcUVITEZZCjl5WVBiUW9PUG1IWnFzVnovVkVL
            TWQycFVjRWdpbWZPNVpuRExsRnpETVkKLS0tIEh3aEF6NFZaTzZZNFhOczA5NTJF
            a1NFenNyblovOFdQQ0p0VjUvWm5za3MKl4dTadwBsyMcfdL83V/UefRlIf5pK9g1
            fW5354xH77s6ZjHd+9lo2s2DK+RK0TbIDud5jgq8zvEL/iqlRsCTrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T21:11:14Z"
    mac: ENC[AES256_GCM,data:K1rTchO3FJKRz6kz0QnlEEyxfHAQw0ElSN6tffFBlogAbqDPUm4mX4LfG+Ld4XqK4MC+pu/uibbWypRMxvWQWjFkhOB39bIisVnPlVuI2lb+VaLIVv3bNNnxWLVJXK5SS97u1WrHLLTZoaeNv8gvNIcXGd7iNgpJdOWuBbL067g=,iv:xG1dASYlK6zKIRM4IAdtE4qpfvHPHumgDHg7fCdTrMk=,tag:5GC177YxGhI6RS7WhbIB7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
