apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:maavijTVcQloPTx19OD1sU/JYcI1onDy3N7lCYT7m3hqU+S6,iv:0aIMMazwyIYEwdSRxFwK9ZaYm96wW904v1hfEIkZ5LY=,tag:R4ygHzaIXuaMggRX1MTPkw==,type:str]
  credentials.json: ENC[AES256_GCM,data:Ah0WUAmrkidiBt7+zB7ujuRWLqHcmijNCOY+XoBSVv4hWxWhBwIQngHyH52MdE19l7C/QiGgzlKAVonIXtV28bd+n+06N+i9WfoUtQxuf8KRn0SyXzsiYb2apS6PskBothPa30maWC7CKWHerngmL/gSY+VnAt9IBt4K8CQc7CrIAvwre4zOQHQTR2FHU+xfH1g8nOvtgxI50nw/PHEHtM5sNU0ZnricuY8TzBK6fg==,iv:n+MXlKI4+62RtsIloscz6ka2obSIX8XRRLDzdhsK6ZY=,tag:0ubs0f15xx87KLyoE0rdDA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q2VoZWhDaTU0MEVWMVEv
        STJ5YVA3aU1sVkEwdDZtR1ozUjczZDVxdVhFCmdiSFZ2eCs2Q1VFN21nSFdKdjh0
        U3czdXZnRWdaWmVFaXE2VTRUaVNGUVEKLS0tIEswRnFKWnZWR1diYXUvUkxHb3ky
        VUFQOWFLNThGT0M4cFZyZ0pOMjhCYk0Kv1Nxm1fopg27/GGaLbpex2+i7k359otU
        KsNKJWDeAGCh2RHxagh5mx4vZ/MKGVYK7hwrVr40Rr3KC4HnsqWVzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-03-17T02:04:01Z"
  mac: ENC[AES256_GCM,data:kx35SQ2cYkL8DVxnNhdxxnS8sfev07lhQl3qHgz7H6qN4FS8yTcnB78ftVfHO6Wzju/LbLQNmTM10Oc2QBJv/anwXKc4G56ufD2CwUfaudq/J7YJealP/Qwpr4C+GGcvxSbXYfpLxweLOQTr+gDYqAwSDNu0ztw1dR0n+4Aquls=,iv:HkD3xLvKXvTfjI0cJ3HPEUJaVv0od8GnU3Ve5lZxSDI=,tag:JdcwAO9N0+Di96cDT77NKA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
