---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kube-vip
spec:
  interval: 30m
  chart:
    spec:
      chart: *name
      # renovate: datasource=helm depName=kube-vip repository=https://kube-vip.github.io/helm-charts
      version: 0.6.2
      sourceRef:
        kind: HelmRepository
        name: *name
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Check https://kube-vip.io/docs/installation/flags/
    env:
      # Mode
      cp_enable: "true"
      svc_enable: "false"
      # VIP Configs
      vip_arp: "true"
      address: "10.1.0.6"
      # vip_interface: ""
      vip_cidr: "32"
      vip_ddns: "false"
      vip_leaderelection: "true"
      lb_enable: "true"
      lb_port: "6443"
      # Leader Election config
      # vip_leaseduration: "15"
      # vip_renewdeadline: "10"
      # vip_retryperiod: "2"
      cp_namespace: "kube-system"
    extraArgs:
      prometheusHTTPServer: ":2112"
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
          - SYS_TIME
    # hostAliases:
    # - hostnames:
    #   - kubernetes
    # ip: 127.0.0.1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
