apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:E8DElLz2GCFz74rJqRakZXPlAVFVXiNkFaoz/WvXNAUlcy4XcTKMwg==,iv:PipruDcNaI8829HThTNgSROj1o2DV24HuieXUZ/UKso=,tag:1XkRfFGwWwFHoopppQRtNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiKzJUWmVMclhWbXpSS0Vr
            T1B5Z3k2OFNEZ3lYZm96bk1ZYmxnR05tQVJnClY4QXF0U28xQXBWUmVIcFFSSzRW
            R3BFK0sxNm4xb3hsZFgzY1E0RmJCdFkKLS0tIHl2ZVdreXpMQ3JwWjkyYTN4TS8x
            V1llc1dTclJ3SDFzcE9qbnA0ZEZ5NGMKT/iyUdzFKeGxzoyVki8GbSrGLY2DBLNq
            l6Dna1LZ7ELnwfxYOJ3Z4itjFlW4LElFX5SEJquHwvY7rJX4Bb4PQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T01:58:51Z"
    mac: ENC[AES256_GCM,data:5ox3PeYZWqoKxYKeumfXn2aeKzaOWkMcbn362K/Cf2fwAy2B6dgmiOX+ESM83Flpe5aXlBjxuwPhsWdwhcdi705FmhzXkEMUA7DODqBcDImdzFuUrnv81VXMD4uCS31GAVXZg1WlaXqEUvsWKj8WQ5V9M7fBW/9yr4Tz2Lbz5kk=,iv:Z2Ykq72PJHQumdoYmzIBr8vPtxWasSAQ8Vav0cF22pk=,tag:U86j5LMBMan/OlfM0pe8xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
