---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  BREWFILE: "{{.ROOT_DIR}}/.taskfiles/workstation/Brewfile"

tasks:
  brew:
    desc: Install workstation dependencies with Brew
    cmd: brew bundle --file {{.BREWFILE}}
    preconditions:
      - { msg: "Missing Homebrew", sh: "command -v brew" }
      - { msg: "Missing Brewfile", sh: "test -f {{.BREWFILE}}" }
