---
- name: Cluster kube-vip
  hosts: master
  serial: 1
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Upgrade kube-vip
      ansible.builtin.template:
        src: templates/kube-vip-ds.yaml.j2
        dest: "/var/lib/k0s/manifests/kube-vip/kube-vip-ds.yaml"
        mode: preserve
