apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:sh7RtOEVlFgV14YgINbmld/mIrseuWOeNmq71JJYNgY=,iv:6h1eZVtIAtTar4p1n1VhG1FoOX2TFc438Rzfgdan9iM=,tag:DGamSQPUOzSCetuc+XcC1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc2N3cVhGeHdpdkZRRWZC
            ZW9rY1dURkh2SjFyYlNNTXFlUEdoT0RDakdzCmpmOUE5ekRHU3Q0Ylh3OFN1K2Nh
            OVNMb1BwQTg1OUVuZHgwdE9TSndwTVkKLS0tIExOREtVSURMcUJkV2hHVkloRndn
            SGlMTHZSMDJobkNhTUpuaDFKamY5aG8KnbMc9ZeFChwtfvWxgUDQTdtx214Vj3e1
            tTqV10TA18O9txw6fm+jWF0/+uEtDvv+d6w2It80/nd84BqWsUZdFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T21:11:14Z"
    mac: ENC[AES256_GCM,data:xMQdXMGkrqG4QIDRUvY121AgfyxRJrLk0gus1rJL64MWsjvgxAVkwoJOTUubD07jichdPv15IuL3rfM6smyHwiY1qgrEV1f2CojMPeO5l3bCdAPiXVHapWH1y+XOdOfik4MQRSeR3FyRtjPvGLv7MLembDgPmhUVRygnTlD0hPs=,iv:D+f/pHQ7YJ0ni/EpZ+/qOkEMSO1JqiY8aRwJX4fx06M=,tag:JFS+hoVJR8O5Fxv3mjE9bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
