---
k3s_control_node: true
k3s_server:
  # Pod CIDR
  cluster-cidr: "10.69.0.0/16"
  # Service CIDr
  service-cidr: "10.96.0.0/16"
  disable: [
      "flannel", # Use custom CNI
      "local-storage", # RPIs don't have any storage
      "metrics-server",
      "servicelb",
      "traefik", # Will install my own IngressClass
    ]
  disable-cloud-controller: true
  disable-kube-proxy: true
  # Use cilium
  disable-network-policy: true
  flannel-backend: "none"
  docker: false
  embedded-registry: true
  etcd-expose-metrics: true
  kube-apiserver-arg:
    - "anonymous-auth=true"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  kubelet-arg:
    # How often to collect gargbage images
    - "image-gc-high-threshold=55"
    - "image-gc-low-threshold=50"
  node-ip: "{{ ansible_host }}"
  # pause-image: registry.k8s.io/pause:3.10
  secrets-encryption: true
  tls-san:
    # kube-vip address
    - "10.1.0.6"
    # custom address
    - "chivel.cluster.local"
    - "chivel.teamkhunglong.com"
  write-kubeconfig-mode: "644"
