apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:3pro7nd97suu0O0G4RBcr1dZc8neUUtzZ0X0EtwGjriJSS6h4fR84w==,iv:2Zq6u6Q28E3qxx0eazn/ftfcccLMbrRrRkREGjvfbmk=,tag:+lPFmYNnO2hOOdxQT1zgRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dEVuQmVoc2cxN3R1Mlls
            d0J1MnRiMWJsc2ZXcDFaSkdKR0ppM1lsYnhRCjYwQ3k5N2l2QXVnK3dlTmxoUjhw
            Tm56OGhETUpvWVRwRmYyTjNrQ01VU0EKLS0tIHZFZjE0RHFBMVVUVmNOa3NTTGNw
            UHZRaU1nTS9VTUowYkl2aDUyaVBER0UKRgXgKmNM4ZwGWBIlZ1Flen1HAGDNuWoz
            oPaZK8y0qoUlL+2xgd+pga3Rtxy1UrwOpnDKPELIHg4v9o3wtyPPeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T00:47:27Z"
    mac: ENC[AES256_GCM,data:oztBFadxGXLx8o8A0tg528ckk0G21ugrpF6f0CsZ5JVXkOFsRPvD8wb6LjD5TFNtmmM7PMa+pvIUOrZ8kiyq6Bh26jmdH6eY1Gu6RwSTiIjDVqsJWrOWXMjMEFtMX5/3VJqbvowZ6wkmZul0uIhGtjVA6cmaT/4vO/wEw43jc4E=,iv:rcp/vAoX3qmCsRmFsUzpWDense/jIs2+AuhKgjM9Ago=,tag:2Y87jeYwLh7vIPAx6moZWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
